/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace ITERC20 {
  export type ConstructorParamsStruct = {
    name: string;
    symbol: string;
    contractURI: string;
    decimals: BigNumberish;
    totalSupplyCap: BigNumberish;
    permissions: BigNumberish;
  };

  export type ConstructorParamsStructOutput = [
    string,
    string,
    string,
    number,
    BigNumber,
    number
  ] & {
    name: string;
    symbol: string;
    contractURI: string;
    decimals: number;
    totalSupplyCap: BigNumber;
    permissions: number;
  };
}

export interface TokenFactoryInterface extends utils.Interface {
  functions: {
    "CREATE_PERMISSION()": FunctionFragment;
    "EXECUTE_PERMISSION()": FunctionFragment;
    "TOKEN_FACTORY_RESOURCE()": FunctionFragment;
    "TOKEN_REGISTRY_DEP()": FunctionFragment;
    "countTokens()": FunctionFragment;
    "deployTERC20((string,string,string,uint8,uint256,uint8))": FunctionFragment;
    "getDeployedTokens()": FunctionFragment;
    "getInjector()": FunctionFragment;
    "isTokenExist(address)": FunctionFragment;
    "listTokens(uint256,uint256)": FunctionFragment;
    "requestTERC20((string,string,string,uint8,uint256,uint8),string)": FunctionFragment;
    "setDependencies(address,bytes)": FunctionFragment;
    "setInjector(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "CREATE_PERMISSION"
      | "EXECUTE_PERMISSION"
      | "TOKEN_FACTORY_RESOURCE"
      | "TOKEN_REGISTRY_DEP"
      | "countTokens"
      | "deployTERC20"
      | "getDeployedTokens"
      | "getInjector"
      | "isTokenExist"
      | "listTokens"
      | "requestTERC20"
      | "setDependencies"
      | "setInjector"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CREATE_PERMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTE_PERMISSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_FACTORY_RESOURCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TOKEN_REGISTRY_DEP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "countTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployTERC20",
    values: [ITERC20.ConstructorParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInjector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenExist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "listTokens",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTERC20",
    values: [ITERC20.ConstructorParamsStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDependencies",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "setInjector", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "CREATE_PERMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTE_PERMISSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_FACTORY_RESOURCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TOKEN_REGISTRY_DEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "countTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployTERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInjector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listTokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestTERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDependencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInjector",
    data: BytesLike
  ): Result;

  events: {
    "DeployedTERC20(address,(string,string,string,uint8,uint256,uint8))": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeployedTERC20"): EventFragment;
}

export interface DeployedTERC20EventObject {
  token: string;
  params: ITERC20.ConstructorParamsStructOutput;
}
export type DeployedTERC20Event = TypedEvent<
  [string, ITERC20.ConstructorParamsStructOutput],
  DeployedTERC20EventObject
>;

export type DeployedTERC20EventFilter = TypedEventFilter<DeployedTERC20Event>;

export interface TokenFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    CREATE_PERMISSION(overrides?: CallOverrides): Promise<[string]>;

    EXECUTE_PERMISSION(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_FACTORY_RESOURCE(overrides?: CallOverrides): Promise<[string]>;

    TOKEN_REGISTRY_DEP(overrides?: CallOverrides): Promise<[string]>;

    countTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    deployTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getDeployedTokens(
      overrides?: CallOverrides
    ): Promise<[string[]] & { tokens_: string[] }>;

    getInjector(
      overrides?: CallOverrides
    ): Promise<[string] & { injector_: string }>;

    isTokenExist(token_: string, overrides?: CallOverrides): Promise<[boolean]>;

    listTokens(
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { tokens_: string[] }>;

    requestTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      description_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setDependencies(
      registryAddress_: string,
      data_: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    setInjector(
      injector_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  CREATE_PERMISSION(overrides?: CallOverrides): Promise<string>;

  EXECUTE_PERMISSION(overrides?: CallOverrides): Promise<string>;

  TOKEN_FACTORY_RESOURCE(overrides?: CallOverrides): Promise<string>;

  TOKEN_REGISTRY_DEP(overrides?: CallOverrides): Promise<string>;

  countTokens(overrides?: CallOverrides): Promise<BigNumber>;

  deployTERC20(
    params_: ITERC20.ConstructorParamsStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getDeployedTokens(overrides?: CallOverrides): Promise<string[]>;

  getInjector(overrides?: CallOverrides): Promise<string>;

  isTokenExist(token_: string, overrides?: CallOverrides): Promise<boolean>;

  listTokens(
    offset_: BigNumberish,
    limit_: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  requestTERC20(
    params_: ITERC20.ConstructorParamsStruct,
    description_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setDependencies(
    registryAddress_: string,
    data_: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  setInjector(
    injector_: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    CREATE_PERMISSION(overrides?: CallOverrides): Promise<string>;

    EXECUTE_PERMISSION(overrides?: CallOverrides): Promise<string>;

    TOKEN_FACTORY_RESOURCE(overrides?: CallOverrides): Promise<string>;

    TOKEN_REGISTRY_DEP(overrides?: CallOverrides): Promise<string>;

    countTokens(overrides?: CallOverrides): Promise<BigNumber>;

    deployTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getDeployedTokens(overrides?: CallOverrides): Promise<string[]>;

    getInjector(overrides?: CallOverrides): Promise<string>;

    isTokenExist(token_: string, overrides?: CallOverrides): Promise<boolean>;

    listTokens(
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    requestTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      description_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDependencies(
      registryAddress_: string,
      data_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setInjector(injector_: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "DeployedTERC20(address,(string,string,string,uint8,uint256,uint8))"(
      token?: null,
      params?: null
    ): DeployedTERC20EventFilter;
    DeployedTERC20(token?: null, params?: null): DeployedTERC20EventFilter;
  };

  estimateGas: {
    CREATE_PERMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    EXECUTE_PERMISSION(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_FACTORY_RESOURCE(overrides?: CallOverrides): Promise<BigNumber>;

    TOKEN_REGISTRY_DEP(overrides?: CallOverrides): Promise<BigNumber>;

    countTokens(overrides?: CallOverrides): Promise<BigNumber>;

    deployTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getDeployedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    getInjector(overrides?: CallOverrides): Promise<BigNumber>;

    isTokenExist(token_: string, overrides?: CallOverrides): Promise<BigNumber>;

    listTokens(
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      description_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setDependencies(
      registryAddress_: string,
      data_: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    setInjector(
      injector_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CREATE_PERMISSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EXECUTE_PERMISSION(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TOKEN_FACTORY_RESOURCE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TOKEN_REGISTRY_DEP(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    countTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getDeployedTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInjector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isTokenExist(
      token_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    listTokens(
      offset_: BigNumberish,
      limit_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestTERC20(
      params_: ITERC20.ConstructorParamsStruct,
      description_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setDependencies(
      registryAddress_: string,
      data_: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    setInjector(
      injector_: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
