export enum IconNames {
  academicCap = 'academic-cap',
  adjustments = 'adjustments',
  annotation = 'annotation',
  archive = 'archive',
  arrowCircleDown = 'arrow-circle-down',
  arrowCircleLeft = 'arrow-circle-left',
  arrowCircleRight = 'arrow-circle-right',
  arrowCircleUp = 'arrow-circle-up',
  arrowDown = 'arrow-down',
  arrowLeft = 'arrow-left',
  checkCircle = 'check-circle',
  check = 'check',
  chevronDown = 'chevron-down',
  exclamationCircle = 'exclamation-circle',
  exclamation = 'exclamation',
  eyeOff = 'eye-off',
  eye = 'eye',
  login = 'login',
  plus = 'plus',
  search = 'search',
  shieldExclamation = 'shield-exclamation',
  truck = 'truck',
  xCircle = 'x-circle',
  x = 'x',
}
